version: '3.8'
services: 
  postgresDB:
    image: postgres:13 
    container_name: timoty_token
    ports:
      - 5432:5432
    volumes: 
      - timoty_token:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - networkName

volumes: 
  timoty_token:
networks:
  networkName:


